spring.application.name=chapterone
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Conexión a la DB
spring.datasource.url=jdbc:mysql://localhost:3306/chapter_one?createDatabaseIfNotExist=true
spring.datasource.username=jpa
spring.datasource.password=santiputo

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Limite de 5MB para los archivos (solo fotos de perfil por ahora)
spring.servlet.multipart.max-file-size=5MB

spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
